--Truncate table OrderStatus
--Truncate table ContactType
--Truncate table EggUnitPrice
Truncate table EggTransaction

drop table Test
Truncate table Delivery
Truncate table OrderClutchCooler
Truncate table OrderFlockClutch
Truncate table OrderIncubatorCart
Truncate table CoolerClutch
Truncate table OrderDeliveryCart
Truncate table OrderIncubatorEggsSetBy
Truncate table DeliveryFlock
Truncate table OrderInvoice

--Truncate table DeliveryCart
delete from DeliveryCart
--Truncate table Clutch
delete from Clutch
--Truncate table Contact
delete from Contact
--Truncate table Flock
delete from Flock
--Truncate table Truck
delete from Truck
--Truncate table OrderFlock
delete from OrderFlock
--Truncate table OrderHoldingIncubator
delete from OrderHoldingIncubator
--Truncate table OrderIncubator
delete from OrderIncubator
--Truncate table [Order]
delete from [Order]
--Truncate table Cooler
delete from Cooler
--Truncate table Destination
delete from Destination
--Truncate table DestinationBuilding
delete from DestinationBuilding
--Truncate table Farm
delete from Farm
--Truncate table HoldingIncubator
delete from HoldingIncubator
--Truncate table Incubator
delete from Incubator
--Truncate table IncubatorCart
delete from IncubatorCart
--Truncate table Invoice
delete from Invoice
